---
# This file is included, when no vars/versions/{{ version }}.yml
#   exists for the configured version.

# default SHA256 sum for the redistributable package
maven_redis_sha256sum: MUST_BE_DEFINED_IN_INVENTORY
